version: 2

updates:
  - package-ecosystem: maven
    directory: /test/gha-test
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
