name: 'Java Maven Build'
description: 'Maven build using a specific version of the Java JDK'
author: 'offa'
inputs:
  java-version:
    description: 'The Java version use'
    required: true
  pmd:
    description: 'Execute PMD'
    required: false
    default: false
  skip-javadoc:
    description: 'Skip generation of JavaDoc'
    required: false
    default: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: 'Setup jdk-${{ inputs.java-version }}'
      uses: actions/setup-java@main
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: 'maven'
    - name: 'Maven Build'
      run: mvn verify --batch-mode -Dmaven.javadoc.skip=${{ inputs.skip-javadoc }} -V --no-transfer-progress
      shell: bash
    - name: 'Execute PMD'
      run: if [[ "${{ inputs.pmd }}" = true ]]; then mvn pmd:pmd --batch-mode --no-transfer-progress; fi
      shell: bash
