name: ci

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17, 21, 25 ]
    name: jdk-${{ matrix.java }}
    steps:
      - uses: actions/checkout@main

      - name: Build
        uses: ./
        with:
          java-version: ${{ matrix.java }}
          pom: test/gha-test
          pmd: true
