name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17, 19 ]
    name: jdk-${{ matrix.java }}
    steps:
      - uses: actions/checkout@main

      - name: Build
        uses: ./
        with:
          java-version: ${{ matrix.java }}
          pom: test/gha-test
          pmd: true
